inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  DisplayCopNames: true
  Exclude:
    - "tmp/**/*"
    - "vendor/**/*"

Metrics/BlockLength:
  Exclude:
    - "hyrax-doi.gemspec"
    - "lib/hyrax/doi/spec/shared_specs/*"
    - "spec/**/*"

Metrics/MethodLength:
  Exclude:
    - "app/controllers/hyrax/doi/hyrax_doi_controller.rb"

Layout/LineLength:
  Exclude:
    - "spec/support/datacite_api_stubs.rb"

Style/RedundantSelf:
  Exclude:
    - "app/services/hyrax/doi/datacite_registrar.rb"

Naming/FileName:
  Exclude:
    - "lib/generators/hyrax/doi/templates/config/initializers/hyrax-doi.rb"

RSpec/ExampleLength:
  Max: 10

RSpec/AnyInstance:
  Exclude:
    - "spec/controllers/hyrax/doi/mint_actions_spec.rb"
    - "spec/services/hyrax/doi/flexible_profile_installer_spec.rb"

RSpec/NestedGroups:
  Enabled: false
