inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - 'spec/internal_test_hyrax/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Metrics/BlockLength:
  Exclude:
    - 'hyrax-doi.gemspec'
    - 'lib/hyrax/doi/spec/shared_specs/*'
    - 'spec/**/*'

Layout/LineLength:
  Exclude:
    - 'spec/support/datacite_api_stubs.rb'

Style/RedundantSelf:
  Exclude:
    - 'app/services/hyrax/doi/datacite_registrar.rb'

Naming/FileName:
  Exclude:
    - 'lib/generators/hyrax/doi/templates/config/initializers/hyrax-doi.rb'

RSpec/ExampleLength:
  Max: 10
  Exclude:
    - 'spec/features/**/*'
    - 'spec/services/bolognese/writers/hyrax_work_writer_spec.rb'

RSpec/AnyInstance:
  Exclude:
    - 'spec/controllers/hyrax_doi_controller_spec.rb'
    - 'spec/features/autofill_spec.rb'
    - 'spec/features/create_draft_doi_spec.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'

RSpec/NestedGroups:
  Enabled: false