inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - 'spec/internal_test_hyrax/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Metrics/BlockLength:
  Exclude:
    - 'lib/hyrax/doi/spec/shared_specs/*'
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/actors/hyrax/actors/doi_actor.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/actors/hyrax/actors/doi_actor.rb'

RSpec/MessageSpies:
  Exclude:
    - 'spec/jobs/hyrax/doi/register_doi_job_spec.rb'

RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/jobs/hyrax/doi/register_doi_job_spec.rb'
