# Place any default configuration for solr_wrapper here
# version: 6.0.0
port: 8983
instance_dir: tmp/solr-development
collection:
  persist: true
  dir: spec/internal_test_hyrax/solr/config/
  name: hydra-development

