version: "3.8"

services:
  fedora:
    image: ghcr.io/samvera/fcrepo4:4.7.5
    ports:
      - "8986:8080" # Test port
    volumes:
      - fedora_data:/opt/fcrepo/data
    environment:
      - CATALINA_OPTS=-Djava.awt.headless=true -Dfile.encoding=UTF-8 -server -Xms512m -Xmx1024m -XX:NewSize=256m -XX:MaxNewSize=256m -XX:PermSize=256m -XX:MaxPermSize=256m -XX:+DisableExplicitGC
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/fcrepo/rest"]
      interval: 30s
      timeout: 10s
      retries: 5

  solr:
    image: solr:9.9
    ports:
      - "8985:8983" # Test port
    volumes:
      - solr_data:/var/solr:cached
      - ./spec/internal_test_hyrax/solr/conf:/opt/solr/server/configsets/hyraxconf
    command:
      - sh
      - -c
      - "precreate-core hyrax-test /opt/solr/server/configsets/hyraxconf; solr-precreate hyrax /opt/solr/server/configsets/hyraxconf"
    ulimits:
      nofile:
        soft: 65536
        hard: 524288
    environment:
      - SOLR_CORE_CONF_DIR=/opt/solr/server/configsets/hyraxconf
      - SOLR_MODULES=analysis-extras,extraction
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983/solr/admin/cores"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  fedora_data:
  solr_data:
