name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  bundle_lint_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: circle_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:6
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    env:
      RAILS_VERSION: 5.2.4.3
      DATABASE_NAME: circle_test
      DATABASE_HOST: localhost
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_TEST_NAME: circle_test
      BUNDLE_PATH: vendor/bundle
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      RAILS_ENV: test
      RACK_ENV: test
      FCREPO_TEST_PORT: 8986
      SPEC_OPTS: --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Ruby 3.3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev

      - name: Start Fedora and Solr services
        run: |
          docker-compose up -d
          # Wait for services to be ready
          timeout 60 bash -c 'until curl -f http://localhost:8986/fcrepo/rest; do echo "Waiting for Fedora..."; sleep 2; done'
          timeout 60 bash -c 'until curl -f http://localhost:8985/solr/admin/cores; do echo "Waiting for Solr..."; sleep 2; done'

      - name: Setup database
        run: |
          bundle exec rake app:db:create app:db:schema:load

      - name: Run Rubocop
        run: bundle exec rubocop

      - name: Run tests
        run: |
          bundle exec rspec
